import Head from 'next/head'
import Image from 'next/image'
import Layout from "../components/Layout"
import homeStyles from "../styles/Home.module.css"

export default function Home() {
  return (
    <div>
      <Head>
        <title>Hassan Saeed - Portfolio</title>
        <meta name="description" content="My portfolio app generated by create next app" />
        <meta name='keywords' content='web development, programming, frontend, web design, web developer' />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <Layout>

<div className={homeStyles.flex}>
      
      <div className={homeStyles.hero}>
      <h2>Hey, I am</h2>
      <h1>Hassan Saeed</h1>
      <h2>Welcome to my Portfolio</h2>
      </div>
     

      <div className={homeStyles.img}>
      </div>
</div>
    </Layout>

    
    </div>
  )
}
